angular.module('SceneSkeleton',['ngRoute','ngResource'])
	.config(['$routeProvider',function($routeProvider){
		$routeProvider
			.when('/scene/new',{
				templateUrl: 'templates/scene/create.html',
				controller:'SceneCreateController'
			})
			.when('/scene/:sceneId',{
				templateUrl:'templates/scene/display.html',
				controller:'SceneDisplayController'
			})
			.when('/scene/',{
				templateUrl:'templates/scene/list.html',
				controller:'SceneListController'
			})
			.when('/',{
				templateUrl:'templates/title.html'
			})
			.otherwise({
				redirectTo:'/'
			});
	}]);